name: budgeit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0-323.2.beta

dependencies:
  cloud_firestore: ^5.2.0
  dropdown_button2: ^2.3.9
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  firebase_database: ^11.0.4
  firebase_storage: ^12.1.2
  flutter:
    sdk: flutter
  flutter_switch: ^0.3.2
  fluttertoast: ^8.2.6
  image_picker: ^1.1.2
  persistent_bottom_nav_bar: ^6.2.1
  provider: ^6.1.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "assets/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit-ExtraBold.ttf
        - asset: assets/fonts/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-SemiBold.ttf
